// braze_compiler.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include <iostream>
#include <sstream>
#include <cctype>
#include <string>
#include "../compiler_lib/braze_compiler.h"
#include "../compiler_lib/source/pch.h"
#include "../compiler_lib/compilerProcess.h"

void printHelpString();

int main(int argc, char* argv[]) {
  std::string input_file;
  std::string output_file;
  std::string output_bin;
  std::shared_ptr<std::stringstream> input_args = std::make_shared<std::stringstream>();
  bool input_file_mode = true;

  if (argc < 2) {
    std::cout << "\n-h -help or help for arg description\n";
    std::cout << "\nNo input file provided, using <project-root>/test_file.c\n";
#if _MSC_VER
    input_file = "./../test_file.c";
#else
    input_file = "./test_file.c";
#endif
    output_file = "./test_file.c.asm";
    output_bin = "./test_file";
  }
  else if (argc < 4)
  {
    if(STRINGS_EQUAL(argv[1], "--input_file"))
    {
      input_file = argv[2];
      output_file = input_file + ".asm";
      output_bin = input_file;
      const std::string suffix = ".c";
      output_bin.erase(input_file.size()-suffix.size());
    }

    if(STRINGS_EQUAL(argv[1], "-h") || STRINGS_EQUAL(argv[1], "-help") || STRINGS_EQUAL(argv[1], "help"))
    {
      printHelpString();
      return 0;
    }
    if(STRINGS_EQUAL(argv[1], "--input_code"))
    {
      *input_args << argv[2];
      output_file = "app.out.asm";
      output_bin = "app.out";
      const std::string suffix = ".c";
      input_file_mode = false;
    }

    if(STRINGS_EQUAL(argv[1], "-h") || STRINGS_EQUAL(argv[1], "-help") || STRINGS_EQUAL(argv[1], "help"))
    {
      printHelpString();
      return 0;
    }
    if (STRINGS_EQUAL(argv[1], "-v") || STRINGS_EQUAL(argv[1], "-version") || STRINGS_EQUAL(argv[1], "version"))
    {
      std::cout << "braze compiler " << BRAZE_VERSION;
      return 0;
    }
  }

  //std::cout <<"\ncompiling " << input_file << " to " << output_bin << "\n\n";

  std::string nasm_output_file = output_bin + ".o";

  //avoid libc debugging, allocato on heap
  compileProcess* process = new compileProcess();
  if(input_file_mode)
    process->initialize(input_file);
  else
    process->initialize(input_args);
  
  
  int ret = process->startCompiler();
  if (ret != 0)
  {
    std::cout << "failed to compile " + input_file + "result: " + std::to_string(ret);
  }
  delete process;

  if(input_file_mode)
  {   
      //nasm -f elf32 ./test_file.c.asm -o ./test_file.o && gcc -m32 ./test_file.o -o ./test_file -no-pie
      std::string nasm_cmd = "nasm -f elf32 ./" + output_file + " -o ./" + nasm_output_file + " && gcc -m32 ./" + nasm_output_file + " -o ./" + output_bin +" -no-pie";
    
      int res = system(nasm_cmd.c_str());
      if (res != 0)
      {
        std::cout << "\n failed to assemble: " << output_file << " with nasm!";
         return res;
      }  
  }
  
//#endif

}


void printHelpString()
{
  std::cout << "\ncall braze with --input_file <file_to_compile>.c or --input_code 'int main {...}'";
  std::cout << "\nif no input flag is defined, braze will compile <project-root>/test_file.c";
  std::cout << "\n<file_to_compile>.asm will be generated with assembly code ";
  std::cout << "\n<file_to_compile>.o will be generated by nasm, as braze don't assemble";
  std::cout << "\nan executable bin named <file_to_compile> (no suffix) will be created ";
  std::cout << "\n\nfor example, call: ./braze --input_file test_file.c \n";
  std::cout << "\nin command mode, no output binary is created. Assembly code is written to cout \n";
  std::cout << "\n-v -version to see version of braze \n";
}