// braze_compiler.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include <iostream>
#include <cctype>
#include <string>
#include "../compiler_lib/source/compiler_lib.cpp"
#include "../compiler_lib/compilerProcess.h"


int main(int argc, char* argv[]) {
  std::string input_file;
  std::string output_file;
  std::string output_bin;

  if (argc < 2) {
    std::cout << "\n-h -help or help for arg description\n";
    std::cout << "\nNo input file provided, using <project-root>/test_file.c\n";
    input_file = "./test_file.c";
    output_file = "./test_file.c.asm";
    output_bin = "./test_file";
  }
  else if (argc < 4)
  {
    if(STRINGS_EQUAL(argv[1], "--input_file"))
    {
      input_file = argv[2];
      output_file = input_file + ".asm";
      output_bin = input_file;
      const std::string suffix = ".c";
      output_bin.erase(input_file.size()-suffix.size());
    }

    if(STRINGS_EQUAL(argv[1], "-h") || STRINGS_EQUAL(argv[1], "-help") || STRINGS_EQUAL(argv[1], "help"))
    {
      std::cout << "\ncall braze with --input_file <file_to_compile>.c";
      std::cout << "\nif no input file is defined, braze will compile <project-root>/test_file.c";
      std::cout << "\n<file_to_compile>.asm will be generated with assembly code ";
      std::cout << "\n<file_to_compile>.o will be generated by nasm, as braze don't assemble";
      std::cout << "\nan executable bin named <file_to_compile> (no suffix) will be created ";
      std::cout << "\n\nfor example, call: ./braze --input_file test_file.c \n";
      return 0;
    }
  }

  std::cout <<"\ncompiling " << input_file << " to " << output_bin << "\n\n";

  std::string nasm_output_file = output_bin + ".o";

  //avoid libc debugging, allocato on heap
  compileProcess* process = new compileProcess();
  process->initialize(input_file);
  
  int ret = process->startCompiler();
  if (ret != 0)
  {
    std::cout << "failed to compile " + input_file + "result: " + std::to_string(ret);
  }
  delete process;


#if defined(_MSC_VER)
  //Microsoft Visual Studio Compile
 std::cout << "\nno NASM support yet, compile with gcc: \n 1. make clean \n 2. make \n .3 ./bin/braze_compiler " ;
#else
  std::string nasm_cmd = "nasm -f elf32 ./" + output_file + " -o ./" + nasm_output_file + " && gcc -m32 ./" + nasm_output_file + " -o ./" + output_bin +" -no-pie";

  int res = system(nasm_cmd.c_str());
  if (res < 0)
  {
      return res;
  }  
  
#endif

}
