name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Configuration type to build.
  BUILD_CONFIGURATION: Release
  PLATFORM: x64  # Ensure this matches your build platform

permissions:
  contents: read

jobs:
  build-braze_compiler:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore braze_compiler.sln  # Ensure this path is correct

    - name: Build braze_compiler Static Library
      run: msbuild braze_compiler/braze_compiler.vcxproj /p:Configuration=${{ env.BUILD_CONFIGURATION }} /verbosity:diagnostic

  build-unit_test:
    runs-on: windows-latest
    needs: build-braze_compiler  # Ensure this job runs after the braze_compiler static library is built

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore braze_compiler.sln  # Ensure this path is correct

    - name: Build unit_test Project
      run: msbuild unit_test/unit_test.vcxproj /p:Configuration=${{ env.BUILD_CONFIGURATION }} /verbosity:diagnostic